databases:
  - name: urlshortener-db
    plan: free
    region: singapore          
    databaseName: urlshortener
    user: urlshortener

services:
  - type: web
    name: url-shortener
    runtime: docker            
    plan: free
    region: singapore          
    healthCheckPath: /health   
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urlshortener-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true    